name: openapi.json in sync

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn install
      - name: Download openapi.json from RedHatInsights/policies-backend-ui@master into ./openapi.json
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          branch: master
          name: openapi.json
          path: ./
          repo: RedHatInsights/policies-ui-backend
      - name: Generate types from openapi.json
        run: yarn schema:policies:generate -i openapi.json && rm openapi.json
      - name: Check differences
        run: >
          [[ -z $(git status --porcelain) ]] ||
          (
            echo "openapi.json types are out of sync, see https://github.com/RedHatInsights/policies-ui-frontend#generating-types-from-openapi-file" &&
            git status &&
            git diff &&
            false
          )
